# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/
language: python

python:
    - "3.6"

install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.50/hugo_0.50_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf public
    - ls
    - pwd

script:
    - hugo
    - ls -a
    - echo $GITHUB_TOKEN
after_script:
    - cd public
    - git init
    - git config --global user.email "352233265@qq.com"
    - git config --global user.name "thinmonkey"
    - ls -al
    - git add .
    - git commit -m 'Travis upate blog'
    - git push --force --quiet "https://${GITHUB_TOKEN}@${GITHUB_REP}" master:master

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - ${SOURCE}
